const PropertyDetail = [
  {
    id: "1",
    Image: "./PropertyImages/house-g36151780b_1280.jpg",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "./PropertyImages/double-bed.png",
    bath: "2 Bathroom",
    bathImage: "./PropertyImages/bath.png",
  },
  {
    id: "2",
    Image: "./PropertyImages/r-architecture-2gDwlIim3Uw-unsplash.jpg",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "./PropertyImages/double-bed.png",
    bath: "2 Bathroom",
    bathImage: "./PropertyImages/bath.png",
  },
  {
    id: "3",
    Image: "./PropertyImages/stephan-bechert-yFV39g6AZ5o-unsplash.jpg",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "./PropertyImages/double-bed.png",
    bath: "2 Bathroom",
    bathImage: "./PropertyImages/bath.png",
  },
  {
    id: "4",
    Image: "./PropertyImages/todd-kent-178j8tJrNlc-unsplash.jpg",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "./PropertyImages/double-bed.png",
    bath: "2 Bathroom",
    bathImage: "./PropertyImages/bath.png",
  },
  {
    id: "5",
    Image: "./PropertyImages/vu-anh-TiVPTYCG_3E-unsplash.jpg",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "./PropertyImages/double-bed.png",
    bath: "2 Bathroom",
    bathImage: "./PropertyImages/bath.png",
  },
  {
    id: "6",
    Image: "./PropertyImages/residence-ge8328143b_1920.jpg",
    heading: "Comfortable Apartment in Palace",
    span: "Popular Properties",
    amount: "From $20K",
    size: "1200 Sqft",
    bed: "2 Bed",
    bedImage: "./PropertyImages/double-bed.png",
    bath: "2 Bathroom",
    bathImage: "./PropertyImages/bath.png",
  },
];
export default PropertyDetail;
